project 'ProjectIOS.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectIOS

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth' 
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'


  target 'ProjectIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectIOSUITests' do
    # Pods for testing
  end

end
